export const UPDATE_VALIDATE_DATA = 'UPDATE_VALIDATE_DATA'
export const FORM_REGISTER = 'FORM_REGISTER'
export const FORM_LOGIN = 'FORM_LOGIN'
export const FEATURE_AUTH = 'FEATURE_AUTH'

export const FEATURE_ADMIN = 'FEATURE_ADMIN'