export const UPDATE_VALIDATE_DATA = 'UPDATE_VALIDATE_DATA'
export const FORM_REGISTER = 'FORM_REGISTER'
export const FORM_LOGIN = 'FORM_LOGIN'
export const FEATURE_AUTH = 'FEATURE_AUTH'

export const FEATURE_ADMIN = 'FEATURE_ADMIN'
export const DASH_BOARD_REDUCER = 'DASH_BOARD_REDUCER'

export const FEATURE_SHOW_ROOM = 'FEATURE_SHOW_ROOM'
export const SHOW_ROOM_REDUCER = 'SHOW_ROOM_REDUCER'

export const FEATURE_PORTFOLIO = 'FEATURE_PORTFOLIO'
export const FEATURE_PORTFOLIO_V1 = 'FEATURE_PORTFOLIO_V1'