export const SEARCH_ROLE = 'SEARCH_ROLE'
export const SEARCH_USER = 'SEARCH_USER'
export const EDIT_ROLE = 'EDIT_ROLE'
export const DELETE_ROLE = 'DELETE_ROLE'
export const EDIT_USER = 'EDIT_USER'
export const DELETE_USER = 'DELETE_USER'